CREATE TABLE IF NOT EXISTS SpringMVC.USER
(
	USER_ID INT UNIQUE NOT NULL AUTO_INCREMENT,
	FIRSTNAME VARCHAR(200) NOT NULL, 
	LASTNAME VARCHAR(200) NOT NULL,
	PASSWORD VARCHAR(200) NOT NULL,
	EMAIL VARCHAR(250) NOT NULL,
	GENDER VARCHAR(10) NOT NULL,
		
	PRIMARY KEY (USER_ID),
	
)ENGINE=InnoDB;

